### ISSUE TITLE
Sugerencias

### ISSUE THREAD

**Issue by durancristhian** [Grispi/Uno_Game#1]
Hola Gri, la idea de este issue es sugerirte cosas para agregar, modificar y corregir.

- Agregar un README: esto parece una pavada pero es re importante. De hecho, en el coronabingo no tengo uno 😅 , está el genérico que me creó next.js cuando inicié el proyecto. Aunque no sea súper detallado, está bueno poner que te motivó a hacerlo, que tecnologías usaste, como se clona y se corre el proyecto, que variables de entorno necesitás, etc. así otras personas pueden colaborar también. Insisto, en el coronabingo no lo tengo hecho y es algo para mejorar, pero en tu caso que es uno de tus primeros proyectos y cuando lo difundas seguro muuucha gente lo va a ver, es una muy buena puerta de entrada. *BONUS*: Hacé una grabación de pantalla o gif mostrando 10 segundos de la pantalla del juego como para tener más impacto.

- Habilitar [esta línea](https://github.com/Grispi/Uno_Game/blob/master/postcss.config.js#L15) donde se active el plugin que elimina estilos de más cuando se buildea el proyecto para producción. Quizás lo comentaste porque algo no funciona? Mirando el css creo que te falta usar [este comentario](https://github.com/durancristhian/coronabingo/blob/master/public/css/styles.css#L1) para poder "encapsular" los estilos que no se deberían eliminar. Fijate en el css del coronabingo.

- No hay un `pages/_document.js`. En este archivo podés configurar la estructura base de HTML que van a tener todas las páginas. Esto te sirve para poner los metatags de Analytics (que lo voy a detallar en otro punto). Podés tomar como guía [el `_document` del coronabingo](https://github.com/durancristhian/coronabingo/blob/master/pages_/_document.tsx) que tiene algunas cositas de más pero que las podés sacar. Sino el [de la documentación](https://nextjs.org/docs/advanced-features/custom-document) te alcanza y sobra.

- [Acá](https://nextjs.org/docs/advanced-features/module-path-aliases) te explica como configurar lo de los alias para dejar de hacer los imports con muchos `../../`.

- [Configurar google analytics](https://github.com/zeit/next.js/tree/canary/examples/with-google-analytics). En el README te explica como hacerlo.

- Te recomendaría que pongas [Sentry](http://sentry.io/). Es un servicio que te va a servir para tener un listado de errores junto con un reporte muy piola de donde ocurrió, en que sistema operativo, que fue lo que la persona fue haciendo hasta que le salió el error y varias cosas más. Aunque no le puedas dar mucha bola al principio te súper sirve para entender al menos CUANTOS errores tenés y después crear issues para pedir ayuda con eso. Yo seguí [este artículo](https://leerob.io/blog/configuring-sentry-for-nextjs-apps) que explica como integrarlo (yo no hice lo de los source maps).

- Te faltan los famosos metatags en el HTML inicial, donde configuras etiquetas en el head que son las que se muestran cuando se comparte el link en redes sociales y en las búsquedas de Google. Copiá y pegá todo lo que está dentro de este [Fragment](https://github.com/durancristhian/coronabingo/blob/master/pages_/_app.tsx#L65) y modificalo con lo que vos le quieras poner. Cuando lleves esos cambios a staging, podés usar el sitio [metatags.io](https://metatags.io/) para probar si todo te quedó bien.

Con respecto al código no me metí mucho, solo miré por arriba y no tengo mucho para aportar :)

Intenté enforcarme en cosas que capaz alguien no te diría y está bueno que les prestes atención.

Recomendación final: no es necesario que te des maña para hacer todo esto. Fijate lo que quieras hacer y lo que no y crea issues con un label de `HELP WANTED` y alguien te los podría pedir como hice yo con el coronabingo. O avisame y te ayudo con eso. Ordenate como te quede cómodo a vos, eso de los issues no es lo mejor, pero al menos es lo primero que alguien va a ver cuando entra a un repo.

**Comment by Grispi** [comment]
Muchas gracias @durancristhian por tus sugerencias y tips!
