### ISSUE TITLE
English version please :)

### ISSUE THREAD

**Issue by miparnisari** [Grispi/Uno_Game#3]

**Comment by Grispi** [comment]
I have this plan for a future version, I'm currently working on it. Thank you for your suggestion, I will let you know when it's ready!!!

**Comment by durancristhian** [comment]
Hello!, I sent a PR (#4) to add the basic support we need in order to have translations. Once it's merged to the `translations` branch, we can start sending small PRs to update the app.

@miparnisari would you like to help us? In the PR I described the following steps

**Comment by Grispi** [comment]
Hello everyone! I have created the issue  https://github.com/Grispi/Uno_Game/issues/5 that explains how to add the translations to English, let me know if you want to contribute!
