### ISSUE TITLE
Translate the app for english version

### ISSUE THREAD

**Issue by Grispi** [Grispi/Uno_Game#5]
We need to translate all the JSON files to English, which are located [here](https://github.com/Grispi/Uno_Game/tree/master/locales/en). 

For reference, you can find the Spanish translation in [this folder](https://github.com/Grispi/Uno_Game/tree/master/locales/es). 

It can be a good idea to send PRs for one file at a time.

The files that need to be translated are:

- [common.json](https://github.com/Grispi/Uno_Game/blob/master/locales/en/common.json) - Used in the [Header](https://github.com/Grispi/Uno_Game/blob/master/components/Header.js),  [Footer](https://github.com/Grispi/Uno_Game/blob/master/components/Footer.js), [Rules](https://github.com/Grispi/Uno_Game/blob/master/components/Rules.js), [unoRules](https://github.com/Grispi/Uno_Game/blob/master/utils/unoRules.js), [Select](https://github.com/Grispi/Uno_Game/blob/master/components/Select.js), [StartGame](https://github.com/Grispi/Uno_Game/blob/master/components/StartGame.js), and [pages_/index](https://github.com/Grispi/Uno_Game/blob/master/pages_/index.js) and [pages_/rooms/index](https://github.com/Grispi/Uno_Game/blob/master/pages_/rooms/%5BroomId%5D/index.js) files.
- [index.json](https://github.com/Grispi/Uno_Game/blob/master/locales/en/index.json) - Used in [pages_/index](https://github.com/Grispi/Uno_Game/blob/master/pages_/index.js) file.
- [playerId.json](https://github.com/Grispi/Uno_Game/blob/master/locales/en/playerId.json) - Used in [playerId](https://github.com/Grispi/Uno_Game/blob/master/pages_/rooms/%5BroomId%5D/players/%5BplayerId%5D.js), [WinnerBoardLayout](https://github.com/Grispi/Uno_Game/blob/master/components/WinnerBoardLayout.js), [WildCardOptions](https://github.com/Grispi/Uno_Game/blob/master/components/WildCardOptions.js), [CurrentMovePlayerOptions](https://github.com/Grispi/Uno_Game/blob/master/components/CurrentMovePlayerOptions.js), [GameInProgress](https://github.com/Grispi/Uno_Game/blob/master/components/GameInProgress.js) files.
- [roomId.json](https://github.com/Grispi/Uno_Game/blob/master/locales/en/roomId.json) - Used in [pages_/rooms/index](https://github.com/Grispi/Uno_Game/blob/master/pages_/rooms/%5BroomId%5D/index.js) file.

Remember to follow the instructions from the [Readme](https://github.com/Grispi/Uno_Game/blob/master/README.md), to run the app.

**Comment by durancristhian** [comment]
Hi!, with Constanza we'd like to take the translations for the `common.json` files.

**Comment by durancristhian** [comment]
Also, I have a person on twitter telling me that will take the files `index.json` and `roomId.json`

**Comment by durancristhian** [comment]
Still missing help for `playerId.json`

**Comment by Grispi** [comment]
> Hi!, with Constanza we'd like to take the translations for the `common.json` files.
 Hello Constanza and Cris, the common file is yours.., thanks for the help!

> Also, I have a person on twitter (Alice) telling me that will take the files `index.json` and `roomId.json`
Perfect, thanks for the help, Alice! These files are yours too.

**Comment by mbyeme** [comment]
Hi @Grispi  I'd like to take playerId.json file.

**Comment by Grispi** [comment]
> Hi @Grispi I'd like to take playerId.json file.

It's yours @mbyeme! thank you for volunteering!!!!

**Comment by jmrosello** [comment]
Hi, if you still need help translating, let me know, I would be glad to help.

**Comment by Grispi** [comment]
> Hi, if you still need help translating, let me know, I would be glad to help.

At the moment, all the files are taken, I will let you know when we need more help...Thank you very much for volunteering!
